---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-monitoring-crd
  namespace: fleet-local
spec:
  branch: main
  paths:
    - fleet/rancher-monitoring-crd
  repo: https://github.com/johnko/rancher-demo.git
  targets:
    - name: local
      clusterSelector:  # match label of Cluster
        matchLabels:
          management.cattle.io/cluster-name: local
