---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubecost
  namespace: fleet-local
spec:
  branch: dev
  paths:
    - fleet/cost-analyzer
  repo: https://github.com/johnko/rancher-demo.git
  targets:
    - name: local
      clusterSelector:  # match label of Cluster
        matchLabels:
          management.cattle.io/cluster-name: local
