---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: argo-cd
  namespace: fleet-default
spec:
  branch: main
  paths:
    - fleet/argo-cd
  repo: https://github.com/johnko/rancher-demo.git
  targets:
    - name: nonp
      clusterGroup: nonp
